name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get yarn cache dir
        id: yarnCache
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-yarn
        with:
          path: ${{ steps.yarnCache.outputs.dir }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        run: yarn install
      - name: Prepare environment
        env:
          API_KEYS: ${{ secrets.API_KEYS }}
          SECRETS: ${{ secrets.SECRETS }}
        run: |
          echo $API_KEYS > app/apiKeys.ts
          echo $SECRETS > secrets.ts
      - name: Test
        run: yarn test
      - name: Build Core
        run: yarn build:core
      - name: Build App
        run: |
          yarn build:client
          yarn build:app
